"""added col completed in session  model

Revision ID: 22910c54b330
Revises: 7f00afe1245f
Create Date: 2024-05-02 19:07:47.907488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22910c54b330'
down_revision = '7f00afe1245f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_history', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
