"""feedback added in session history model

Revision ID: 6ca73cc293e4
Revises: 22910c54b330
Create Date: 2024-05-08 12:19:23.063288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca73cc293e4'
down_revision = '22910c54b330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_history', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
