"""added exercise  model

Revision ID: 90f6fc71f28e
Revises: 5b897637d96d
Create Date: 2024-05-02 16:37:03.831415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f6fc71f28e'
down_revision = '5b897637d96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plank_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('incorrect', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plank_exercises')
    # ### end Alembic commands ###
